// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lego.proto

#ifndef PROTOBUF_lego_2eproto__INCLUDED
#define PROTOBUF_lego_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3003002 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace lego {
class LegoRecord;
class LegoRecordDefaultTypeInternal;
extern LegoRecordDefaultTypeInternal _LegoRecord_default_instance_;
class LegoRecordField;
class LegoRecordFieldDefaultTypeInternal;
extern LegoRecordFieldDefaultTypeInternal _LegoRecordField_default_instance_;
class LegoRecordSection;
class LegoRecordSectionDefaultTypeInternal;
extern LegoRecordSectionDefaultTypeInternal _LegoRecordSection_default_instance_;
class LegoResponse;
class LegoResponseDefaultTypeInternal;
extern LegoResponseDefaultTypeInternal _LegoResponse_default_instance_;
}  // namespace lego

namespace lego {

namespace protobuf_lego_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_lego_2eproto

// ===================================================================

class LegoRecordField : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:lego.LegoRecordField) */ {
 public:
  LegoRecordField();
  virtual ~LegoRecordField();

  LegoRecordField(const LegoRecordField& from);

  inline LegoRecordField& operator=(const LegoRecordField& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const LegoRecordField& default_instance();

  static inline const LegoRecordField* internal_default_instance() {
    return reinterpret_cast<const LegoRecordField*>(
               &_LegoRecordField_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(LegoRecordField* other);

  // implements Message ----------------------------------------------

  inline LegoRecordField* New() const PROTOBUF_FINAL { return New(NULL); }

  LegoRecordField* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const LegoRecordField& from);
  void MergeFrom(const LegoRecordField& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(LegoRecordField* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string id = 1;
  void clear_id();
  static const int kIdFieldNumber = 1;
  const ::std::string& id() const;
  void set_id(const ::std::string& value);
  #if LANG_CXX11
  void set_id(::std::string&& value);
  #endif
  void set_id(const char* value);
  void set_id(const char* value, size_t size);
  ::std::string* mutable_id();
  ::std::string* release_id();
  void set_allocated_id(::std::string* id);

  // string name = 2;
  void clear_name();
  static const int kNameFieldNumber = 2;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  #if LANG_CXX11
  void set_name(::std::string&& value);
  #endif
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // string data = 3;
  void clear_data();
  static const int kDataFieldNumber = 3;
  const ::std::string& data() const;
  void set_data(const ::std::string& value);
  #if LANG_CXX11
  void set_data(::std::string&& value);
  #endif
  void set_data(const char* value);
  void set_data(const char* value, size_t size);
  ::std::string* mutable_data();
  ::std::string* release_data();
  void set_allocated_data(::std::string* data);

  // @@protoc_insertion_point(class_scope:lego.LegoRecordField)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr id_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::internal::ArenaStringPtr data_;
  mutable int _cached_size_;
  friend struct protobuf_lego_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class LegoRecordSection : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:lego.LegoRecordSection) */ {
 public:
  LegoRecordSection();
  virtual ~LegoRecordSection();

  LegoRecordSection(const LegoRecordSection& from);

  inline LegoRecordSection& operator=(const LegoRecordSection& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const LegoRecordSection& default_instance();

  static inline const LegoRecordSection* internal_default_instance() {
    return reinterpret_cast<const LegoRecordSection*>(
               &_LegoRecordSection_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(LegoRecordSection* other);

  // implements Message ----------------------------------------------

  inline LegoRecordSection* New() const PROTOBUF_FINAL { return New(NULL); }

  LegoRecordSection* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const LegoRecordSection& from);
  void MergeFrom(const LegoRecordSection& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(LegoRecordSection* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .lego.LegoRecordField fields = 3;
  int fields_size() const;
  void clear_fields();
  static const int kFieldsFieldNumber = 3;
  const ::lego::LegoRecordField& fields(int index) const;
  ::lego::LegoRecordField* mutable_fields(int index);
  ::lego::LegoRecordField* add_fields();
  ::google::protobuf::RepeatedPtrField< ::lego::LegoRecordField >*
      mutable_fields();
  const ::google::protobuf::RepeatedPtrField< ::lego::LegoRecordField >&
      fields() const;

  // string id = 1;
  void clear_id();
  static const int kIdFieldNumber = 1;
  const ::std::string& id() const;
  void set_id(const ::std::string& value);
  #if LANG_CXX11
  void set_id(::std::string&& value);
  #endif
  void set_id(const char* value);
  void set_id(const char* value, size_t size);
  ::std::string* mutable_id();
  ::std::string* release_id();
  void set_allocated_id(::std::string* id);

  // string name = 2;
  void clear_name();
  static const int kNameFieldNumber = 2;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  #if LANG_CXX11
  void set_name(::std::string&& value);
  #endif
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // @@protoc_insertion_point(class_scope:lego.LegoRecordSection)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::lego::LegoRecordField > fields_;
  ::google::protobuf::internal::ArenaStringPtr id_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  mutable int _cached_size_;
  friend struct protobuf_lego_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class LegoRecord : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:lego.LegoRecord) */ {
 public:
  LegoRecord();
  virtual ~LegoRecord();

  LegoRecord(const LegoRecord& from);

  inline LegoRecord& operator=(const LegoRecord& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const LegoRecord& default_instance();

  static inline const LegoRecord* internal_default_instance() {
    return reinterpret_cast<const LegoRecord*>(
               &_LegoRecord_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(LegoRecord* other);

  // implements Message ----------------------------------------------

  inline LegoRecord* New() const PROTOBUF_FINAL { return New(NULL); }

  LegoRecord* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const LegoRecord& from);
  void MergeFrom(const LegoRecord& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(LegoRecord* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .lego.LegoRecordSection sections = 3;
  int sections_size() const;
  void clear_sections();
  static const int kSectionsFieldNumber = 3;
  const ::lego::LegoRecordSection& sections(int index) const;
  ::lego::LegoRecordSection* mutable_sections(int index);
  ::lego::LegoRecordSection* add_sections();
  ::google::protobuf::RepeatedPtrField< ::lego::LegoRecordSection >*
      mutable_sections();
  const ::google::protobuf::RepeatedPtrField< ::lego::LegoRecordSection >&
      sections() const;

  // string id = 1;
  void clear_id();
  static const int kIdFieldNumber = 1;
  const ::std::string& id() const;
  void set_id(const ::std::string& value);
  #if LANG_CXX11
  void set_id(::std::string&& value);
  #endif
  void set_id(const char* value);
  void set_id(const char* value, size_t size);
  ::std::string* mutable_id();
  ::std::string* release_id();
  void set_allocated_id(::std::string* id);

  // string name = 2;
  void clear_name();
  static const int kNameFieldNumber = 2;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  #if LANG_CXX11
  void set_name(::std::string&& value);
  #endif
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // @@protoc_insertion_point(class_scope:lego.LegoRecord)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::lego::LegoRecordSection > sections_;
  ::google::protobuf::internal::ArenaStringPtr id_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  mutable int _cached_size_;
  friend struct protobuf_lego_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class LegoResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:lego.LegoResponse) */ {
 public:
  LegoResponse();
  virtual ~LegoResponse();

  LegoResponse(const LegoResponse& from);

  inline LegoResponse& operator=(const LegoResponse& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const LegoResponse& default_instance();

  static inline const LegoResponse* internal_default_instance() {
    return reinterpret_cast<const LegoResponse*>(
               &_LegoResponse_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    3;

  void Swap(LegoResponse* other);

  // implements Message ----------------------------------------------

  inline LegoResponse* New() const PROTOBUF_FINAL { return New(NULL); }

  LegoResponse* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const LegoResponse& from);
  void MergeFrom(const LegoResponse& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(LegoResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 success = 1;
  void clear_success();
  static const int kSuccessFieldNumber = 1;
  ::google::protobuf::int32 success() const;
  void set_success(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:lego.LegoResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 success_;
  mutable int _cached_size_;
  friend struct protobuf_lego_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// LegoRecordField

// string id = 1;
inline void LegoRecordField::clear_id() {
  id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& LegoRecordField::id() const {
  // @@protoc_insertion_point(field_get:lego.LegoRecordField.id)
  return id_.GetNoArena();
}
inline void LegoRecordField::set_id(const ::std::string& value) {
  
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:lego.LegoRecordField.id)
}
#if LANG_CXX11
inline void LegoRecordField::set_id(::std::string&& value) {
  
  id_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:lego.LegoRecordField.id)
}
#endif
inline void LegoRecordField::set_id(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:lego.LegoRecordField.id)
}
inline void LegoRecordField::set_id(const char* value, size_t size) {
  
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:lego.LegoRecordField.id)
}
inline ::std::string* LegoRecordField::mutable_id() {
  
  // @@protoc_insertion_point(field_mutable:lego.LegoRecordField.id)
  return id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* LegoRecordField::release_id() {
  // @@protoc_insertion_point(field_release:lego.LegoRecordField.id)
  
  return id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void LegoRecordField::set_allocated_id(::std::string* id) {
  if (id != NULL) {
    
  } else {
    
  }
  id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), id);
  // @@protoc_insertion_point(field_set_allocated:lego.LegoRecordField.id)
}

// string name = 2;
inline void LegoRecordField::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& LegoRecordField::name() const {
  // @@protoc_insertion_point(field_get:lego.LegoRecordField.name)
  return name_.GetNoArena();
}
inline void LegoRecordField::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:lego.LegoRecordField.name)
}
#if LANG_CXX11
inline void LegoRecordField::set_name(::std::string&& value) {
  
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:lego.LegoRecordField.name)
}
#endif
inline void LegoRecordField::set_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:lego.LegoRecordField.name)
}
inline void LegoRecordField::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:lego.LegoRecordField.name)
}
inline ::std::string* LegoRecordField::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:lego.LegoRecordField.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* LegoRecordField::release_name() {
  // @@protoc_insertion_point(field_release:lego.LegoRecordField.name)
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void LegoRecordField::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:lego.LegoRecordField.name)
}

// string data = 3;
inline void LegoRecordField::clear_data() {
  data_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& LegoRecordField::data() const {
  // @@protoc_insertion_point(field_get:lego.LegoRecordField.data)
  return data_.GetNoArena();
}
inline void LegoRecordField::set_data(const ::std::string& value) {
  
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:lego.LegoRecordField.data)
}
#if LANG_CXX11
inline void LegoRecordField::set_data(::std::string&& value) {
  
  data_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:lego.LegoRecordField.data)
}
#endif
inline void LegoRecordField::set_data(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:lego.LegoRecordField.data)
}
inline void LegoRecordField::set_data(const char* value, size_t size) {
  
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:lego.LegoRecordField.data)
}
inline ::std::string* LegoRecordField::mutable_data() {
  
  // @@protoc_insertion_point(field_mutable:lego.LegoRecordField.data)
  return data_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* LegoRecordField::release_data() {
  // @@protoc_insertion_point(field_release:lego.LegoRecordField.data)
  
  return data_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void LegoRecordField::set_allocated_data(::std::string* data) {
  if (data != NULL) {
    
  } else {
    
  }
  data_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), data);
  // @@protoc_insertion_point(field_set_allocated:lego.LegoRecordField.data)
}

// -------------------------------------------------------------------

// LegoRecordSection

// string id = 1;
inline void LegoRecordSection::clear_id() {
  id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& LegoRecordSection::id() const {
  // @@protoc_insertion_point(field_get:lego.LegoRecordSection.id)
  return id_.GetNoArena();
}
inline void LegoRecordSection::set_id(const ::std::string& value) {
  
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:lego.LegoRecordSection.id)
}
#if LANG_CXX11
inline void LegoRecordSection::set_id(::std::string&& value) {
  
  id_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:lego.LegoRecordSection.id)
}
#endif
inline void LegoRecordSection::set_id(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:lego.LegoRecordSection.id)
}
inline void LegoRecordSection::set_id(const char* value, size_t size) {
  
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:lego.LegoRecordSection.id)
}
inline ::std::string* LegoRecordSection::mutable_id() {
  
  // @@protoc_insertion_point(field_mutable:lego.LegoRecordSection.id)
  return id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* LegoRecordSection::release_id() {
  // @@protoc_insertion_point(field_release:lego.LegoRecordSection.id)
  
  return id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void LegoRecordSection::set_allocated_id(::std::string* id) {
  if (id != NULL) {
    
  } else {
    
  }
  id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), id);
  // @@protoc_insertion_point(field_set_allocated:lego.LegoRecordSection.id)
}

// string name = 2;
inline void LegoRecordSection::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& LegoRecordSection::name() const {
  // @@protoc_insertion_point(field_get:lego.LegoRecordSection.name)
  return name_.GetNoArena();
}
inline void LegoRecordSection::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:lego.LegoRecordSection.name)
}
#if LANG_CXX11
inline void LegoRecordSection::set_name(::std::string&& value) {
  
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:lego.LegoRecordSection.name)
}
#endif
inline void LegoRecordSection::set_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:lego.LegoRecordSection.name)
}
inline void LegoRecordSection::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:lego.LegoRecordSection.name)
}
inline ::std::string* LegoRecordSection::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:lego.LegoRecordSection.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* LegoRecordSection::release_name() {
  // @@protoc_insertion_point(field_release:lego.LegoRecordSection.name)
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void LegoRecordSection::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:lego.LegoRecordSection.name)
}

// repeated .lego.LegoRecordField fields = 3;
inline int LegoRecordSection::fields_size() const {
  return fields_.size();
}
inline void LegoRecordSection::clear_fields() {
  fields_.Clear();
}
inline const ::lego::LegoRecordField& LegoRecordSection::fields(int index) const {
  // @@protoc_insertion_point(field_get:lego.LegoRecordSection.fields)
  return fields_.Get(index);
}
inline ::lego::LegoRecordField* LegoRecordSection::mutable_fields(int index) {
  // @@protoc_insertion_point(field_mutable:lego.LegoRecordSection.fields)
  return fields_.Mutable(index);
}
inline ::lego::LegoRecordField* LegoRecordSection::add_fields() {
  // @@protoc_insertion_point(field_add:lego.LegoRecordSection.fields)
  return fields_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::lego::LegoRecordField >*
LegoRecordSection::mutable_fields() {
  // @@protoc_insertion_point(field_mutable_list:lego.LegoRecordSection.fields)
  return &fields_;
}
inline const ::google::protobuf::RepeatedPtrField< ::lego::LegoRecordField >&
LegoRecordSection::fields() const {
  // @@protoc_insertion_point(field_list:lego.LegoRecordSection.fields)
  return fields_;
}

// -------------------------------------------------------------------

// LegoRecord

// string id = 1;
inline void LegoRecord::clear_id() {
  id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& LegoRecord::id() const {
  // @@protoc_insertion_point(field_get:lego.LegoRecord.id)
  return id_.GetNoArena();
}
inline void LegoRecord::set_id(const ::std::string& value) {
  
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:lego.LegoRecord.id)
}
#if LANG_CXX11
inline void LegoRecord::set_id(::std::string&& value) {
  
  id_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:lego.LegoRecord.id)
}
#endif
inline void LegoRecord::set_id(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:lego.LegoRecord.id)
}
inline void LegoRecord::set_id(const char* value, size_t size) {
  
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:lego.LegoRecord.id)
}
inline ::std::string* LegoRecord::mutable_id() {
  
  // @@protoc_insertion_point(field_mutable:lego.LegoRecord.id)
  return id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* LegoRecord::release_id() {
  // @@protoc_insertion_point(field_release:lego.LegoRecord.id)
  
  return id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void LegoRecord::set_allocated_id(::std::string* id) {
  if (id != NULL) {
    
  } else {
    
  }
  id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), id);
  // @@protoc_insertion_point(field_set_allocated:lego.LegoRecord.id)
}

// string name = 2;
inline void LegoRecord::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& LegoRecord::name() const {
  // @@protoc_insertion_point(field_get:lego.LegoRecord.name)
  return name_.GetNoArena();
}
inline void LegoRecord::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:lego.LegoRecord.name)
}
#if LANG_CXX11
inline void LegoRecord::set_name(::std::string&& value) {
  
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:lego.LegoRecord.name)
}
#endif
inline void LegoRecord::set_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:lego.LegoRecord.name)
}
inline void LegoRecord::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:lego.LegoRecord.name)
}
inline ::std::string* LegoRecord::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:lego.LegoRecord.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* LegoRecord::release_name() {
  // @@protoc_insertion_point(field_release:lego.LegoRecord.name)
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void LegoRecord::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:lego.LegoRecord.name)
}

// repeated .lego.LegoRecordSection sections = 3;
inline int LegoRecord::sections_size() const {
  return sections_.size();
}
inline void LegoRecord::clear_sections() {
  sections_.Clear();
}
inline const ::lego::LegoRecordSection& LegoRecord::sections(int index) const {
  // @@protoc_insertion_point(field_get:lego.LegoRecord.sections)
  return sections_.Get(index);
}
inline ::lego::LegoRecordSection* LegoRecord::mutable_sections(int index) {
  // @@protoc_insertion_point(field_mutable:lego.LegoRecord.sections)
  return sections_.Mutable(index);
}
inline ::lego::LegoRecordSection* LegoRecord::add_sections() {
  // @@protoc_insertion_point(field_add:lego.LegoRecord.sections)
  return sections_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::lego::LegoRecordSection >*
LegoRecord::mutable_sections() {
  // @@protoc_insertion_point(field_mutable_list:lego.LegoRecord.sections)
  return &sections_;
}
inline const ::google::protobuf::RepeatedPtrField< ::lego::LegoRecordSection >&
LegoRecord::sections() const {
  // @@protoc_insertion_point(field_list:lego.LegoRecord.sections)
  return sections_;
}

// -------------------------------------------------------------------

// LegoResponse

// int32 success = 1;
inline void LegoResponse::clear_success() {
  success_ = 0;
}
inline ::google::protobuf::int32 LegoResponse::success() const {
  // @@protoc_insertion_point(field_get:lego.LegoResponse.success)
  return success_;
}
inline void LegoResponse::set_success(::google::protobuf::int32 value) {
  
  success_ = value;
  // @@protoc_insertion_point(field_set:lego.LegoResponse.success)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace lego

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_lego_2eproto__INCLUDED
