// Code generated by protoc-gen-go. DO NOT EDIT.
// source: lego.proto

/*
Package lego is a generated protocol buffer package.

It is generated from these files:
	lego.proto

It has these top-level messages:
	LegoRecordField
	LegoRecordSection
	LegoRecord
	LegoResponse
*/
package lego

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LegoRecordField struct {
	Id   string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Data string `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
}

func (m *LegoRecordField) Reset()                    { *m = LegoRecordField{} }
func (m *LegoRecordField) String() string            { return proto.CompactTextString(m) }
func (*LegoRecordField) ProtoMessage()               {}
func (*LegoRecordField) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *LegoRecordField) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *LegoRecordField) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LegoRecordField) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type LegoRecordSection struct {
	Id     string             `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name   string             `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Fields []*LegoRecordField `protobuf:"bytes,3,rep,name=fields" json:"fields,omitempty"`
}

func (m *LegoRecordSection) Reset()                    { *m = LegoRecordSection{} }
func (m *LegoRecordSection) String() string            { return proto.CompactTextString(m) }
func (*LegoRecordSection) ProtoMessage()               {}
func (*LegoRecordSection) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *LegoRecordSection) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *LegoRecordSection) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LegoRecordSection) GetFields() []*LegoRecordField {
	if m != nil {
		return m.Fields
	}
	return nil
}

type LegoRecord struct {
	Id       string               `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name     string               `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Sections []*LegoRecordSection `protobuf:"bytes,3,rep,name=sections" json:"sections,omitempty"`
}

func (m *LegoRecord) Reset()                    { *m = LegoRecord{} }
func (m *LegoRecord) String() string            { return proto.CompactTextString(m) }
func (*LegoRecord) ProtoMessage()               {}
func (*LegoRecord) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *LegoRecord) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *LegoRecord) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LegoRecord) GetSections() []*LegoRecordSection {
	if m != nil {
		return m.Sections
	}
	return nil
}

type LegoResponse struct {
	Success int32 `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (m *LegoResponse) Reset()                    { *m = LegoResponse{} }
func (m *LegoResponse) String() string            { return proto.CompactTextString(m) }
func (*LegoResponse) ProtoMessage()               {}
func (*LegoResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *LegoResponse) GetSuccess() int32 {
	if m != nil {
		return m.Success
	}
	return 0
}

func init() {
	proto.RegisterType((*LegoRecordField)(nil), "lego.LegoRecordField")
	proto.RegisterType((*LegoRecordSection)(nil), "lego.LegoRecordSection")
	proto.RegisterType((*LegoRecord)(nil), "lego.LegoRecord")
	proto.RegisterType((*LegoResponse)(nil), "lego.LegoResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Lego service

type LegoClient interface {
	SendRecord(ctx context.Context, in *LegoRecord, opts ...grpc.CallOption) (*LegoResponse, error)
}

type legoClient struct {
	cc *grpc.ClientConn
}

func NewLegoClient(cc *grpc.ClientConn) LegoClient {
	return &legoClient{cc}
}

func (c *legoClient) SendRecord(ctx context.Context, in *LegoRecord, opts ...grpc.CallOption) (*LegoResponse, error) {
	out := new(LegoResponse)
	err := grpc.Invoke(ctx, "/lego.Lego/SendRecord", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Lego service

type LegoServer interface {
	SendRecord(context.Context, *LegoRecord) (*LegoResponse, error)
}

func RegisterLegoServer(s *grpc.Server, srv LegoServer) {
	s.RegisterService(&_Lego_serviceDesc, srv)
}

func _Lego_SendRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LegoRecord)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LegoServer).SendRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lego.Lego/SendRecord",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LegoServer).SendRecord(ctx, req.(*LegoRecord))
	}
	return interceptor(ctx, in, info, handler)
}

var _Lego_serviceDesc = grpc.ServiceDesc{
	ServiceName: "lego.Lego",
	HandlerType: (*LegoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendRecord",
			Handler:    _Lego_SendRecord_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lego.proto",
}

func init() { proto.RegisterFile("lego.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 220 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0xcd, 0x6a, 0x85, 0x30,
	0x14, 0x84, 0xf1, 0xa7, 0xb6, 0x3d, 0x2d, 0xfd, 0x09, 0x94, 0x86, 0xae, 0x24, 0x2b, 0x37, 0x75,
	0xa1, 0xbb, 0x3e, 0x40, 0xa1, 0xd0, 0x55, 0x7c, 0x02, 0x9b, 0x1c, 0x25, 0x60, 0x13, 0x31, 0xde,
	0xf7, 0xbf, 0x24, 0xd1, 0xeb, 0xc5, 0x95, 0xbb, 0xc9, 0x9c, 0x61, 0xbe, 0x81, 0x00, 0x0c, 0xd8,
	0x9b, 0x72, 0x9c, 0xcc, 0x6c, 0x48, 0xea, 0x34, 0xfb, 0x81, 0xe7, 0x5f, 0xec, 0x0d, 0x47, 0x61,
	0x26, 0xf9, 0xad, 0x70, 0x90, 0xe4, 0x09, 0x62, 0x25, 0x69, 0x94, 0x47, 0xc5, 0x3d, 0x8f, 0x95,
	0x24, 0x04, 0x52, 0xdd, 0xfe, 0x23, 0x8d, 0xbd, 0xe3, 0xb5, 0xf3, 0x64, 0x3b, 0xb7, 0x34, 0x09,
	0x9e, 0xd3, 0xac, 0x83, 0xd7, 0xad, 0xaa, 0x41, 0x31, 0x2b, 0xa3, 0x0f, 0x95, 0x7d, 0x42, 0xd6,
	0x39, 0xb2, 0xa5, 0x49, 0x9e, 0x14, 0x0f, 0xd5, 0x5b, 0xe9, 0x67, 0xee, 0x76, 0xf1, 0x25, 0xc4,
	0x10, 0x60, 0x3b, 0x1d, 0x02, 0xd4, 0x70, 0x67, 0xc3, 0x9e, 0x15, 0xf1, 0xbe, 0x47, 0x2c, 0x7b,
	0xf9, 0x25, 0xc8, 0x0a, 0x78, 0x0c, 0x67, 0x3b, 0x1a, 0x6d, 0x91, 0x50, 0xb8, 0xb5, 0x27, 0x21,
	0xd0, 0x5a, 0x4f, 0xbb, 0xe1, 0xeb, 0xb3, 0xfa, 0x82, 0xd4, 0x25, 0x49, 0x05, 0xd0, 0xa0, 0x96,
	0xcb, 0xb0, 0x97, 0x3d, 0xe2, 0x83, 0x5c, 0x3b, 0xa1, 0xf5, 0x2f, 0xf3, 0x9f, 0x51, 0x9f, 0x03,
	0x00, 0x00, 0xff, 0xff, 0xce, 0x2b, 0xf6, 0xf7, 0x9a, 0x01, 0x00, 0x00,
}
